### ISSUE TITLE
_io.so: wrong ELF class: ELFCLASS32

### ISSUE THREAD

**Issue by curzel-it** [kivy/plyer#128]
I'm currently using ubuntu 14.04, 64 bit.
Kivy is working fine and I have no problems compiling android apps with buildozer.

I've just installed the library running :
python setup.py install

I've the added the library in the buildozer.specs, before kivy.
Compiling distributions, the error in object occurs.

Relevant log : 
    Call build_plyer
    Entering in ARM environment
    Compiler found at /home/curzel/android-ndk-r10d/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin//arm-linux-androideabi-gcc
    running install
    Traceback (most recent call last):
      File "setup.py", line 52, in <module>
        'Programming Language :: Python :: 3.3',
      File "/home/curzel/python-for-android/build/python-install/lib/python2.7/distutils/core.py", line 152, in setup
        dist.run_commands()
      File "/home/curzel/python-for-android/build/python-install/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/home/curzel/python-for-android/build/python-install/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/curzel/python-for-android/build/python-install/lib/python2.7/site-packages/setuptools/command/install.py", line 76, in run
        self.do_egg_install()
      File "/home/curzel/python-for-android/build/python-install/lib/python2.7/site-packages/setuptools/command/install.py", line 85, in do_egg_install
        easy_install = self.distribution.get_command_class('easy_install')
      File "/home/curzel/python-for-android/build/python-install/lib/python2.7/site-packages/setuptools/dist.py", line 395, in get_command_class
        self.cmdclass[command] = cmdclass = ep.load()
      File "/home/curzel/python-for-android/build/python-install/lib/python2.7/site-packages/pkg_resources.py", line 1954, in load
        entry = **import**(self.module_name, globals(),globals(), ['**name**'])
      File "/home/curzel/python-for-android/build/python-install/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 12, in <module>
        import sys, os.path, zipimport, shutil, tempfile, zipfile, re, stat, random
      File "/home/curzel/python-for-android/build/python-install/lib/python2.7/zipfile.py", line 6, in <module>
        import io
      File "/home/curzel/python-for-android/build/python-install/lib/python2.7/io.py", line 60, in <module>
        import _io
    ImportError: /home/curzel/python-for-android/build/python-install/lib/python2.7/lib-dynload/_io.so: wrong ELF class: ELFCLASS32
    # Command failed: ./distribute.sh -m "sqlite3 setuptools plyer kivy" -d "contacts"
##

**Comment by thegrymek** [comment]
Hi, 

Here's is simmilar problem. 
https://github.com/kivy/python-for-android/issues/234

There are some problems that appears when kivy is installed from sources. 

Let buildozer download kivy itself. This way you avoid `elf` type errors.

ps. for me pyjinius installed and compiled from source didnt work as well in android. Buildozer has to download that package and compile on his own

**Comment by akshayaurora** [comment]
Thanks to @ecdsa who tracked this down on this machine. Try to uninstall cython and install it using apt-get instead of pip.

**Comment by radiodee1** [comment]
I too have this error.

I tried both versions of cython and the error persists. do you have any other suggestions?

**Comment by KeyWeeUsr** [comment]
Closing due to very old P4A toolchain reference (`distribute.sh`). Try with the latest python-for-android release or create an issue there.
