### ISSUE TITLE
uniqueid.id fails under android and windows7 32bit python2.7

### ISSUE THREAD

**Issue by selobu** [kivy/plyer#277]
Hi, I'm trying to get the uniqueid:

from plyer import uniqueid
uniqueid.id

If I use win32 without compyling then returns me a correct value but if I compile the code under windows then fails, also under android and shows me the following error:

`
Traceback (most recent call last):
 File "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/plyer/utils.py", line 67, in _ensure_obj
   mod = __import__(module, fromlist='.')
 File "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/plyer/platforms/android/__init__.py", line 2, in <module>
   from jnius import autoclass
 File "/QPython/QPython2-core/build/python-install/lib/python2.7/site-packages/jnius/__init__.py", line 13, in <module>
 File "/QPython/QPython2-core/build/python-install/lib/python2.7/site-packages/jnius/reflect.py", line 9, in <module>
 File "jnius_export_class.pxi", line 44, in jnius.jnius.MetaJavaClass.__new__ (jnius/jnius.c:13255)
SystemError: NULL result without error in PyObject_Call
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/plyer/utils.py", line 82, in __getattribute__
   return getattr(object.__getattribute__(self, '_obj'), name)
 File "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/plyer/facades.py", line 392, in id
   return self.get_uid()
 File "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/plyer/facades.py", line 395, in get_uid
   return self._get_uid()
 File "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/plyer/facades.py", line 400, in _get_uid
   raise NotImplementedError()
NotImplementedError
`
[kivy groups discusion issue ](https://groups.google.com/forum/#!topic/kivy-users/Bub_xkzuWyM)

**Comment by KeyWeeUsr** [comment]
> Under android it's possible to use the following code

>from jnius import autoclass
>activity = autoclass('org.renpy.android.PythonActivity').mActivity
>Secure = autoclass('android.provider.Settings$Secure')
>machine_id = Secure.getString(activity.getContentResolver(),  Secure.ANDROID_ID)

> You just need to inspect the plyer code to get the windows equivalent code related to plyer.uniqueid

ref: https://groups.google.com/d/msg/kivy-users/Bub_xkzuWyM/KWEvG0H5BwAJ

The exact same code is already in the repository. Perhaps using `autoclass(`org.qpython.qpy.PythonActivity')` would do in case they do have this structure → `org/qpython/qpy/PythonActivity.java` in their project. This isn't a standard usage on Android supported by p4a + plyer, therefore you'd need to customize probably each call using `Activity` within plyer because QPython might not have `org/kivy/android/PythonActivity.java` or `org/renpy/android/PythonActivity.java`. Closing.
