### ISSUE TITLE
TypeError when running examples in Python 3

### ISSUE THREAD

**Issue by mbrockman1** [kivy/plyer#392]
$python3 ./plyer/examples/battery/main.py

[INFO   ] [Kivy        ] v1.10.1.dev0, git-be946b5, 20171102
[INFO   ] [Python      ] v3.6.5 (default, Mar 30 2018, 06:41:53)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'2.1 NVIDIA-10.30.31 355.11.10.10.30.120'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'NVIDIA GeForce GT 650M OpenGL Engine'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.20'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "main.py", line 56, in <module>
     app.run()
   File "/usr/local/lib/python3.6/site-packages/kivy/app.py", line 829, in run
     runTouchApp()
   File "/usr/local/lib/python3.6/site-packages/kivy/base.py", line 502, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/local/lib/python3.6/site-packages/kivy/core/window/window_sdl2.py", line 720, in mainloop
     self._mainloop()
   File "/usr/local/lib/python3.6/site-packages/kivy/core/window/window_sdl2.py", line 457, in _mainloop
     EventLoop.idle()
   File "/usr/local/lib/python3.6/site-packages/kivy/base.py", line 340, in idle
     self.dispatch_input()
   File "/usr/local/lib/python3.6/site-packages/kivy/base.py", line 325, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/usr/local/lib/python3.6/site-packages/kivy/base.py", line 231, in post_dispatch_input
     listener.dispatch('on_motion', etype, me)
   File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "/usr/local/lib/python3.6/site-packages/kivy/core/window/__init__.py", line 1334, in on_motion
     self.dispatch('on_touch_down', me)
   File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "/usr/local/lib/python3.6/site-packages/kivy/core/window/__init__.py", line 1350, in on_touch_down
     if w.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "/usr/local/lib/python3.6/site-packages/kivy/uix/widget.py", line 457, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "/usr/local/lib/python3.6/site-packages/kivy/uix/widget.py", line 457, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "/usr/local/lib/python3.6/site-packages/kivy/uix/behaviors/button.py", line 151, in on_touch_down
     self.dispatch('on_press')
   File "kivy/_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1098, in kivy._event.EventObservers._dispatch
   File "/usr/local/lib/python3.6/site-packages/kivy/lang/builder.py", line 64, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "<string>", line 11, in <module>
   File "main.py", line 41, in get_status
     self.lbl1.text = str(battery.status['isCharging'])
   File "/usr/local/lib/python3.6/site-packages/plyer-1.3.1.dev0-py3.6.egg/plyer/utils.py", line 103, in __getattribute__
     return getattr(object.__getattribute__(self, '_obj'), name)
   File "/usr/local/lib/python3.6/site-packages/plyer-1.3.1.dev0-py3.6.egg/plyer/facades/battery.py", line 42, in status
     return self.get_state()
   File "/usr/local/lib/python3.6/site-packages/plyer-1.3.1.dev0-py3.6.egg/plyer/facades/battery.py", line 45, in get_state
     return self._get_state()
   File "/usr/local/lib/python3.6/site-packages/plyer-1.3.1.dev0-py3.6.egg/plyer/platforms/macosx/battery.py", line 28, in _get_state
     if 'IsCharging' in l:
 TypeError: a bytes-like object is required, not 'str'

**Comment by KeyWeeUsr** [comment]
@mbrockman1 Try with the latest release (`1.3.1`), it should be already fixed.
