### ISSUE TITLE
kivy-ios fails to build plyer

### ISSUE THREAD

**Issue by GoBig87** [kivy/plyer#417]
I'm trying to build plyer for ios and I'm running into this error.  Looks like there's something wrong with my local python package and hostpython or something...
 
Mac:kivy-ios MacUser$ ./toolchain.py build plyer
Want to build ['plyer']
Loaded recipe plyer (depends of ['python', 'pyobjus'], optional are [])
Loaded recipe python (depends of ['hostpython', 'libffi'], optional are ['openssl'])
Loaded recipe pyobjus (depends of ['python'], optional are [])
Loaded recipe hostpython (depends of ['hostlibffi'], optional are ['openssl'])
Loaded recipe libffi (depends of [], optional are [])
Loaded recipe hostlibffi (depends of [], optional are [])
Build order is ['hostlibffi', 'libffi', 'openssl', 'hostpython', 'python', 'pyobjus', 'plyer']
Include dir added: {arch.arch}/hostlibffi
Include dir added: {arch.arch}/libffi
Include dir added: {arch.arch}/openssl
Global: hostpython located at /Users/MacUser/PycharmProjects/Fin-KivyMD-Branch/.buildozer/ios/platform/kivy-ios/dist/hostpython/bin/python
Global: hostpgen located at /Users/MacUser/PycharmProjects/Fin-KivyMD-Branch/.buildozer/ios/platform/kivy-ios/dist/hostpython/bin/pgen
# (ignored) Download hostlibffi
# (ignored) Extract hostlibffi
Build hostlibffi for x86_64 (filtered)
# (ignored) Build hostlibffi
# (ignored) Download libffi
# (ignored) Extract libffi
# (ignored) Build_all libffi
# (ignored) Download openssl
# (ignored) Extract openssl
# (ignored) Build_all openssl
# (ignored) Download hostpython
# (ignored) Extract hostpython
# (ignored) Build_all hostpython
# (ignored) Download python
# (ignored) Extract python
# (ignored) Build_all python
# (ignored) Download pyobjus
# (ignored) Extract pyobjus
# (ignored) Build_all pyobjus
# (ignored) Download plyer
# (ignored) Extract plyer
Build_all plyer
Build plyer for i386 (filtered)
# (ignored) Build plyer
Install include files for plyer
# (ignored) Install_include plyer
Install frameworks for plyer
# (ignored) Install_frameworks plyer
Install sources for plyer
# (ignored) Install_sources plyer
Install plyer
Install plyer
Install plyer into the site-packages
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
/Users/MacUser/PycharmProjects/Fin-KivyMD-Branch/.buildozer/ios/platform/kivy-ios/dist/hostpython/lib/python2.7/site-packages/setuptools/dist.py:333: UserWarning: Normalizing '1.3.1dev' to '1.3.1.dev0'
normalized_version,
running install
Checking .pth file support in /Users/MacUser/PycharmProjects/Fin-KivyMD-Branch/.buildozer/ios/platform/kivy-ios/build/plyer/i386/plyer-master/iosbuild/lib/python2.7/site-packages/
/Users/MacUser/PycharmProjects/Fin-KivyMD-Branch/.buildozer/ios/platform/kivy-ios/dist/hostpython/bin/python -E -c pass
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
TEST FAILED: /Users/MacUser/PycharmProjects/Fin-KivyMD-Branch/.buildozer/ios/platform/kivy-ios/build/plyer/i386/plyer-master/iosbuild/lib/python2.7/site-packages/ does NOT support .pth files
error: bad install directory or PYTHONPATH
You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from. The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:
/Users/MacUser/PycharmProjects/Fin-KivyMD-Branch/.buildozer/ios/platform/kivy-ios/build/plyer/i386/plyer-master/iosbuild/lib/python2.7/site-packages/
and your PYTHONPATH environment variable currently contains:
''
Here are some of your options for correcting the problem:
* You can choose a different installation directory, i.e., one that is
on PYTHONPATH or supports .pth files
* You can add the installation directory to the PYTHONPATH environment
variable. (It must then also be on PYTHONPATH whenever you run
Python and want to use the package(s) you are installing.)
* You can set up the installation directory to support ".pth" files by
using one of the approaches described here:
https://setuptools.readthedocs.io/en/latest/easy_install.html#custom-installation-locations
Please make the appropriate changes for your system and try again.
Traceback (most recent call last):
File "./toolchain.py", line 1319, in <module>
ToolchainCL()
File "./toolchain.py", line 1089, in __init__
getattr(self, args.command)()
File "./toolchain.py", line 1113, in build
build_recipes(args.recipe, ctx)
File "./toolchain.py", line 981, in build_recipes
recipe.execute()
File "/Users/MacUser/PycharmProjects/Fin-KivyMD-Branch/.buildozer/ios/platform/kivy-ios/toolchain.py", line 591, in execute
self.build_all()
File "/Users/MacUser/PycharmProjects/Fin-KivyMD-Branch/.buildozer/ios/platform/kivy-ios/toolchain.py", line 56, in _cache_execution
f(self, *args, **kwargs)
File "/Users/MacUser/PycharmProjects/Fin-KivyMD-Branch/.buildozer/ios/platform/kivy-ios/toolchain.py", line 705, in build_all
self.install()
File "/Users/MacUser/PycharmProjects/Fin-KivyMD-Branch/.buildozer/ios/platform/kivy-ios/toolchain.py", line 56, in _cache_execution
f(self, *args, **kwargs)
File "/Users/MacUser/PycharmProjects/Fin-KivyMD-Branch/.buildozer/ios/platform/kivy-ios/toolchain.py", line 842, in install
self.install_python_package()
File "/Users/MacUser/PycharmProjects/Fin-KivyMD-Branch/.buildozer/ios/platform/kivy-ios/toolchain.py", line 871, in install_python_package
_env=env)
File "/Users/MacUser/PycharmProjects/Fin-KivyMD-Branch/.buildozer/ios/platform/kivy-ios/toolchain.py", line 39, in shprint
for line in command(*args, **kwargs):
File "./tools/external/sh.py", line 565, in next
self.wait()
File "./tools/external/sh.py", line 500, in wait
self.handle_command_exit_code(exit_code)
File "./tools/external/sh.py", line 516, in handle_command_exit_code
raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_1: 
RAN: '/Users/MacUser/PycharmProjects/Fin-KivyMD-Branch/.buildozer/ios/platform/kivy-ios/dist/hostpython/bin/python setup.py install -O2 --prefix /Users/MacUser/PycharmProjects/Fin-KivyMD-Branch/.buildozer/ios/platform/kivy-ios/build/plyer/i386/plyer-master/iosbuild'
STDOUT:
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
/Users/MacUser/PycharmProjects/Fin-KivyMD-Branch/.buildozer/ios/platform/kivy-ios/dist/hostpython/lib/python2.7/site-packages/setuptools/dist.py:333: UserWarning: Normalizing '1.3.1dev' to '1.3.1.dev0'
normalized_version,
running install
Checking .pth file support in /Users/MacUser/PycharmProjects/Fin-KivyMD-Branch/.buildozer/ios/platform/kivy-ios/build/plyer/i386/plyer-master/iosbuild/lib/python2.7/site-packages/
/Users/MacUser/PycharmProjects/Fin-KivyMD-Branch/.buildozer/ios/platform/kivy-ios/dist/hostpython/bin/python -E -c pass
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <pref... (1373 more, please see e.stdout)
STDERR:

**Comment by KeyWeeUsr** [comment]
Doesn't seem like a `plyer` issue to me (nothing `plyer`-ish there). Try to use the instructions from the log. I haven't run `kivy-ios`, but that would be the first thing I'd try.

**Comment by GoBig87** [comment]
Looks to be similar to this issue. https://github.com/kivy/kivy-ios/issues/127

**Comment by GoBig87** [comment]
I think I fixed it.  There was an issue with the recipe setting the hostpython location and site-package path.  I added the install function to the kivy-ios recipe and it built the plyer module for me.

```
# pure-python package, this can be removed when we'll support any python package
from toolchain import PythonRecipe, shprint
from os.path import join
import sh, os

class PlyerRecipe(PythonRecipe):
    version = "master"
    url = "https://github.com/kivy/plyer/archive/{version}.zip"
    depends = ["python", "pyobjus"]
    archs = ["i386"]
    
     #My function I added
    def install(self):
        arch = list(self.filtered_archs)[0]
        build_dir = self.get_build_dir(arch.arch)
        os.chdir(build_dir)
        hostpython = sh.Command(self.ctx.hostpython)
        build_env = arch.get_env()
        dest_dir = join(self.ctx.dist_dir, "root", "python")
        build_env['PYTHONPATH'] = join(dest_dir, 'lib', 'python2.7', 'site-packages')
        cmd = sh.Command("sed")
        shprint(cmd, "-i", "", "s/setuptools/distutils.core/g", "./setup.py", _env=build_env)
        shprint(hostpython, "setup.py", "install", "--prefix", dest_dir, _env=build_env)

recipe = PlyerRecipe()
```
