### ISSUE TITLE
Windows notification - NotImplementedError: No usable implementation found!

### ISSUE THREAD

**Issue by aquaristar** [kivy/plyer#485]
Python == 3.7.1
Windows 10
Plyer == 1.3.2
PyInstaller == 3.4

After I packed exe file with PyInstaller I got following error when I run notify.

Traceback (most recent call last):
   File "main.py", line 57, in <module>
   File "venv\lib\site-packages\kivy\app.py", line 826, in run
   File "venv\lib\site-packages\kivy\base.py", line 502, in runTouchApp
   File "venv\lib\site-packages\kivy\core\window\window_sdl2.py", line 727, in mainloop
   File "venv\lib\site-packages\kivy\core\window\window_sdl2.py", line 460, in _mainloop
   File "venv\lib\site-packages\kivy\base.py", line 340, in idle
   File "venv\lib\site-packages\kivy\base.py", line 325, in dispatch_input
   File "venv\lib\site-packages\kivy\base.py", line 231, in post_dispatch_input
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "venv\lib\site-packages\kivy\core\window\__init__.py", line 1360, in on_motion
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "venv\lib\site-packages\kivy\core\window\__init__.py", line 1376, in on_touch_down
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "venv\lib\site-packages\kivy\uix\widget.py", line 460, in on_touch_down
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "venv\lib\site-packages\kivy\uix\behaviors\button.py", line 151, in on_touch_down
   File "kivy\_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1098, in kivy._event.EventObservers._dispatch
   File "venv\lib\site-packages\kivy\lang\builder.py", line 64, in custom_callback
   File "D:\PycharmProjects\AbcAlarm\dist\abcalarm\notificationdemo.kv", line 22, in <module>
     on_press: root.do_notify(mode='normal')
   File "main.py", line 45, in do_notify
   File "venv\lib\site-packages\plyer\facades\notification.py", line 57, in notify
   File "venv\lib\site-packages\plyer\facades\notification.py", line 62, in _notify
 NotImplementedError: No usable implementation found!
[12896] Failed to execute script main

class NotificationDemo(BoxLayout):

    def do_notify(self, mode='normal'):
        title = self.ids.notification_title.text
        message = self.ids.notification_text.text
        ticker = self.ids.ticker_text.text
        if PY2:
            title = title.decode('utf8')
            message = message.decode('utf8')
        kwargs = {'title': title, 'message': message, 'ticker': ticker}

        if mode == 'fancy':
            kwargs['app_name'] = "Plyer Notification Example"
            if platform == "win":
                kwargs['app_icon'] = join(dirname(realpath(__file__)),
                                          'plyer-icon.ico')
                kwargs['timeout'] = 4
            else:
                kwargs['app_icon'] = join(dirname(realpath(__file__)),
                                          'plyer-icon.png')
        notification.notify(**kwargs)

**Comment by KeyWeeUsr** [comment]
Try to `print(plyer.utils.platform)`, because I think the problem is with a platform value being `unknown` for some weird reason. Otherwise you'd actually get some real error. This issue is just a `Proxy` not being able to get `plyer.platforms.win.notification.instance()` value and therefore it just returns the default `Proxy` value i.e. `plyer.facades.notification.Notification`.

Quick workaround for that is to use the platform specific module directly (`plyer.platforms.win.notification.instance()`).

**Comment by brsaylor** [comment]
I was having a similar issue with the FileChooser on macos, and I solved it by adding the platform-specific module to `hiddenimports` in the spec file. For this issue, the change would be something like:

```
a = Analysis(
   ...
   hiddenimports=['plyer.platforms.win.notification'],
   ...
```

**Comment by samuelkazeem** [comment]
@brsaylor `hiddenimports `did the trick

**Comment by aquaristar** [comment]
@brsaylor , Thanks for your help.
I didn't import plyer notification explicitly.
