### ISSUE TITLE
Notifications do not work when python is frozen.

### ISSUE THREAD

**Issue by r58Playz** [kivy/plyer#507]

**Comment by r58Playz** [comment]
Windows:
frozen with win32 python 3.7
```
Traceback (most recent call last):
  File "C:\Users\toshi\AppData\Roaming\Python\Python37\site-packages\plyer\utils.py", line 96, in _ensure_obj
    mod = __import__(module, fromlist='.')
ModuleNotFoundError: No module named 'plyer.platforms.win.notification'
Exception in thread notifications:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Python37-32\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\toshi\MicroHat\applications\games\factories\astrocraft-python\globals.py", line 47, in r
    plyer.notification.notify(APP_NAME, noti, APP_NAME, ico)
  File "C:\Users\toshi\AppData\Roaming\Python\Python37\site-packages\plyer\facades\notification.py", line 84, in notify
    timeout=timeout, ticker=ticker, toast=toast
  File "C:\Users\toshi\AppData\Roaming\Python\Python37\site-packages\plyer\facades\notification.py", line 90, in _notify
    raise NotImplementedError("No usable implementation found!")
NotImplementedError: No usable implementation found!
```

**Comment by r58Playz** [comment]
Linux:
frozen with OpenSUSE Leap x86_64bit(I do not know what this is) python 3.6 

The traceback is very similar to the windows traceback.

Both executables were frozen using cx_Freeze.

![image](https://user-images.githubusercontent.com/45221816/61162207-71b4ec00-a4bc-11e9-86bf-20680a8d08d1.png)

**Comment by tomgold182** [comment]
I had tons of errors while trying to use python 3.7 with kivy and buildozer.
Try use Python 3.6

**Comment by Julian-O** [comment]
👋 Sorry to hear you are having difficulties; Kivy unites a number of different technologies, so building apps can be temperamental.

We try to use GitHub issues only to track work for developers to do to fix bugs and add new features to Buildozer. This issue should be closed, because it doesn't describe a bug in Buildozer.

There is a mailing list and a Discord channel to support Kivy users debugging their own systems, which should be able to help. They are linked in the [ReadMe](https://github.com/kivy/buildozer#support).

Of course, if it turns out you have stumbled over a bug in Buildozer, we do want to hear about it here. The support channels should be able to help you craft an appropriate bug report.
