### ISSUE TITLE
Vibrator is not working on Android

### ISSUE THREAD

**Issue by goffi-contrib** [kivy/plyer#509]
Hello,

this issue may be related to https://github.com/kivy/plyer/issues/501 but is not exactly the same.
Vibrator is not working at all on Android, the following code:
```python
from plyer import vibrator
vibrator.vibrate()
```
Crash as follow:
```
Traceback (most recent call last): 
  File "<console>", line 1, in <module> 
  File "/home/goffi/.local/share/python-for-android/build/python-installs/cagou_dev_build/plyer/facades/vibrator.py", line 52, in vibrate 
  File "/home/goffi/.local/share/python-for-android/build/python-installs/cagou_dev_build/plyer/platforms/android/vibrator.py", line 24, in _vibrate 
  File "jnius/jnius_export_class.pxi", line 1034, in jnius.jnius.JavaMultipleMethod.__call__ 
JavaException: No methods matching your arguments, available: [u'(ILjava/lang/String;[JILandroid/media/AudioAttributes;)V', u'(ILjava/lang/String;JLandroid/media/AudioAttributes;)V']
```

I've tried with Pyjnius and had the same result. The API 26 deprecation should not affect the code here, I'm building with API 28 but running on AP 23 (Android 6).

This issue has also been reported by somebody else at https://groups.google.com/forum/#!topic/kivy-users/rT9P-mmv0RE and on the chat, but without any solution provided.

**Comment by YakuIt** [comment]
I'm running into this as well. I'm building for API 27, and running on API 25.

I've found that I can call vibration successfully when I use pyjnius 1.2.0. However when I build again using pyjnius commit https://github.com/kivy/pyjnius/commit/6553ad4409782fd1c37247c64736f4aa698a00b2 I get the error.

**Comment by akshayaurora** [comment]
@YakuIt @goffi-contrib can one of you folks please post your bulldozer.spec so I can test ?

**Comment by goffi-contrib** [comment]
@akshayaurora I'm running P4A directly, and I'm using this config: https://repos.goffi.org/cagou/file/tip/.p4a (I have a debug shell allowing to test directly on Android in my app). I did test on Python 2 but my code is now ported to Python 3 and I haven't yet tried to rebuild the Android apk (but I doubt that Python version has anything to do with that anyway).

**Comment by goffi-contrib** [comment]
@akshayaurora I've now ported my apk to Python 3 and tested again:
```python
>>> import plyer 
>>> plyer.__version__ 
'1.4.2' 
>>> from plyer import vibrator 
>>> vibrator.vibrate() 
Traceback (most recent call last): 
  File "<console>", line 1, in <module> 
  File "/home/goffi/.local/share/python-for-android/build/python-installs/cagou_dev_build/plyer/facades/vibrator.py", line 52, in vibrate 
  File "/home/goffi/.local/share/python-for-android/build/python-installs/cagou_dev_build/plyer/platforms/android/vibrator.py", line 24, in _vibrate 
  File "jnius/jnius_export_class.pxi", line 1034, in jnius.jnius.JavaMultipleMethod.__call__ 
jnius.jnius.JavaException: No methods matching your arguments, available: ['(ILjava/lang/String;JLandroid/media/AudioAttributes;)V', '(ILjava/lang/String;[JILandroid/media/AudioAttributes;)V'] 
```

So this is still failing.

**Comment by aldwinaldwin** [comment]
I have the same issue:

https://github.com/kivy/pyjnius/issues/442

**Comment by goffi-contrib** [comment]
I can confirm this works with git version thanks to @Franccisco patch, I'm closing this issue.
