### ISSUE TITLE
IOS - GPS : 'IosGPS' object has no attribute '_location_manager'

### ISSUE THREAD

**Issue by wasimafser** [kivy/plyer#538]
I'm trying to build a application in kivy which requires the user to click on the button to get his / her location.

It runs fine in OsX and throws NotImplementedError, but in the simulator with IPhone x pro max runnig IOS 13.3 it gives me the following error : 

```
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "/Users/matrix/Documents/DEVELOPMENT/SIGNODRONE/APP/signodrone-ios/YourApp/main.py", line 59, in <module>
   File "/Users/matrix/Library/Developer/CoreSimulator/Devices/3FCC9CFD-55DA-41AB-9D01-025F2CE94E03/data/Containers/Bundle/Application/AD415E6D-497E-4097-B94B-F75160ED3B05/signodrone.app/lib/python3.7/site-packages/kivy/app.py", line 950, in run
     runTouchApp()
   File "/Users/matrix/Library/Developer/CoreSimulator/Devices/3FCC9CFD-55DA-41AB-9D01-025F2CE94E03/data/Containers/Bundle/Application/AD415E6D-497E-4097-B94B-F75160ED3B05/signodrone.app/lib/python3.7/site-packages/kivy/base.py", line 560, in runTouchApp
     EventLoop.mainloop()
   File "/Users/matrix/Library/Developer/CoreSimulator/Devices/3FCC9CFD-55DA-41AB-9D01-025F2CE94E03/data/Containers/Bundle/Application/AD415E6D-497E-4097-B94B-F75160ED3B05/signodrone.app/lib/python3.7/site-packages/kivy/base.py", line 334, in mainloop
     self.idle()
   File "/Users/matrix/Library/Developer/CoreSimulator/Devices/3FCC9CFD-55DA-41AB-9D01-025F2CE94E03/data/Containers/Bundle/Application/AD415E6D-497E-4097-B94B-F75160ED3B05/signodrone.app/lib/python3.7/site-packages/kivy/base.py", line 378, in idle
     self.dispatch_input()
   File "/Users/matrix/Library/Developer/CoreSimulator/Devices/3FCC9CFD-55DA-41AB-9D01-025F2CE94E03/data/Containers/Bundle/Application/AD415E6D-497E-4097-B94B-F75160ED3B05/signodrone.app/lib/python3.7/site-packages/kivy/base.py", line 329, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/Users/matrix/Library/Developer/CoreSimulator/Devices/3FCC9CFD-55DA-41AB-9D01-025F2CE94E03/data/Containers/Bundle/Application/AD415E6D-497E-4097-B94B-F75160ED3B05/signodrone.app/lib/python3.7/site-packages/kivy/base.py", line 235, in post_dispatch_input
     listener.dispatch('on_motion', etype, me)
   File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "/Users/matrix/Library/Developer/CoreSimulator/Devices/3FCC9CFD-55DA-41AB-9D01-025F2CE94E03/data/Containers/Bundle/Application/AD415E6D-497E-4097-B94B-F75160ED3B05/signodrone.app/lib/python3.7/site-packages/kivy/core/window/__init__.py", line 1411, in on_motion
     self.dispatch('on_touch_up', me)
   File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "/Users/matrix/Library/Developer/CoreSimulator/Devices/3FCC9CFD-55DA-41AB-9D01-025F2CE94E03/data/Containers/Bundle/Application/AD415E6D-497E-4097-B94B-F75160ED3B05/signodrone.app/lib/python3.7/site-packages/kivy/core/window/__init__.py", line 1447, in on_touch_up
     if w.dispatch('on_touch_up', touch):
   File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "/Users/matrix/Library/Developer/CoreSimulator/Devices/3FCC9CFD-55DA-41AB-9D01-025F2CE94E03/data/Containers/Bundle/Application/AD415E6D-497E-4097-B94B-F75160ED3B05/signodrone.app/lib/python3.7/site-packages/kivy/uix/widget.py", line 567, in on_touch_up
     if child.dispatch('on_touch_up', touch):
   File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "/Users/matrix/Library/Developer/CoreSimulator/Devices/3FCC9CFD-55DA-41AB-9D01-025F2CE94E03/data/Containers/Bundle/Application/AD415E6D-497E-4097-B94B-F75160ED3B05/signodrone.app/lib/python3.7/site-packages/kivy/uix/scrollview.py", line 896, in on_touch_up
     if self.dispatch('on_scroll_stop', touch):
   File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "/Users/matrix/Library/Developer/CoreSimulator/Devices/3FCC9CFD-55DA-41AB-9D01-025F2CE94E03/data/Containers/Bundle/Application/AD415E6D-497E-4097-B94B-F75160ED3B05/signodrone.app/lib/python3.7/site-packages/kivy/uix/scrollview.py", line 935, in on_scroll_stop
     self.simulate_touch_down(touch)
   File "/Users/matrix/Library/Developer/CoreSimulator/Devices/3FCC9CFD-55DA-41AB-9D01-025F2CE94E03/data/Containers/Bundle/Application/AD415E6D-497E-4097-B94B-F75160ED3B05/signodrone.app/lib/python3.7/site-packages/kivy/uix/scrollview.py", line 643, in simulate_touch_down
     ret = super(ScrollView, self).on_touch_down(touch)
   File "/Users/matrix/Library/Developer/CoreSimulator/Devices/3FCC9CFD-55DA-41AB-9D01-025F2CE94E03/data/Containers/Bundle/Application/AD415E6D-497E-4097-B94B-F75160ED3B05/signodrone.app/lib/python3.7/site-packages/kivy/uix/widget.py", line 545, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "/Users/matrix/Library/Developer/CoreSimulator/Devices/3FCC9CFD-55DA-41AB-9D01-025F2CE94E03/data/Containers/Bundle/Application/AD415E6D-497E-4097-B94B-F75160ED3B05/signodrone.app/lib/python3.7/site-packages/kivy/uix/widget.py", line 545, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "/Users/matrix/Library/Developer/CoreSimulator/Devices/3FCC9CFD-55DA-41AB-9D01-025F2CE94E03/data/Containers/Bundle/Application/AD415E6D-497E-4097-B94B-F75160ED3B05/signodrone.app/lib/python3.7/site-packages/kivy/uix/behaviors/button.py", line 151, in on_touch_down
     self.dispatch('on_press')
   File "kivy/_event.pyx", line 705, in kivy._event.EventDispatcher.dispatch
   File "kivy/_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1132, in kivy._event.EventObservers._dispatch
   File "/Users/matrix/Library/Developer/CoreSimulator/Devices/3FCC9CFD-55DA-41AB-9D01-025F2CE94E03/data/Containers/Bundle/Application/AD415E6D-497E-4097-B94B-F75160ED3B05/signodrone.app/lib/python3.7/site-packages/kivy/lang/builder.py", line 57, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "/Users/matrix/Library/Developer/CoreSimulator/Devices/3FCC9CFD-55DA-41AB-9D01-025F2CE94E03/data/Containers/Bundle/Application/AD415E6D-497E-4097-B94B-F75160ED3B05/signodrone.app/YourApp/main.kv", line 36, in <module>
     on_press: Factory.RequestHelpPopup().open()
   File "/Users/matrix/Documents/DEVELOPMENT/SIGNODRONE/APP/signodrone-ios/YourApp/main.py", line 17, in __init__
   File "/Users/matrix/Library/Developer/CoreSimulator/Devices/3FCC9CFD-55DA-41AB-9D01-025F2CE94E03/data/Containers/Bundle/Application/AD415E6D-497E-4097-B94B-F75160ED3B05/signodrone.app/lib/python3.7/site-packages/plyer/facades/gps.py", line 79, in start
     self._start(minTime=minTime, minDistance=minDistance)
   File "/Users/matrix/Library/Developer/CoreSimulator/Devices/3FCC9CFD-55DA-41AB-9D01-025F2CE94E03/data/Containers/Bundle/Application/AD415E6D-497E-4097-B94B-F75160ED3B05/signodrone.app/lib/python3.7/site-packages/plyer/platforms/ios/gps.py", line 20, in _start
     self._location_manager.delegate = self
 AttributeError: 'IosGPS' object has no attribute '_location_manager'
2020-02-01 17:15:13.881462+0530 signodrone[58949:4905314] Application quit abnormally!
2020-02-01 17:15:13.930988+0530 signodrone[58949:4905314] Leaving
```

and also, i see in the example that requesting permissions is only shown for android. 
is there a way to request permission for location in IOS ?

I quite don't understand the argument '_location_manager' ,  but i guess it's the location manager of that specific platform ?  and because i'm not having permissions ( in IOS ) it can't talk with the location manager ?

Someone please let me know how to solve this.
Thanks in Advance.

**Comment by wasimafser** [comment]
UPDATE: 
The Location services seems to Work, but only the second time when i open the popup to fetch location for ( i don't know why ).

I used try-except to just go throught the gps.start() part to see what happens.

**Comment by wasimafser** [comment]
So, i've configured the GPS before starting GPS ( gps.configure() before gps.start() ) and now there's no error.

but the on_location function never seems to be trigerred as mentioned here .... https://github.com/kivy/plyer/issues/173#issue-110302114

I cannot start GPS with the APP as it is going to be used in zones with power-cut, because it will use up the battery left out for em.

so, i'm calling these functions while showing a popup that asks the user of their location.

Got it till here, Someone please help me now !

**Comment by wasimafser** [comment]
It's Done ! I Solved it ! Thanks for the work !

**Comment by muslehm** [comment]
Hey Wasim, I'm facing the same problem. I fixed the first as you did, putting start after config, but then similar to you, I don't get an error, but the on_location doesn't seem to be triggered

**Comment by wasimafser** [comment]
> May you please help me with this? How did you fix it?

If i'm correct then you are also using a simulator. Which means, we should explicitly provide the location for the device. In the simulator menu search for an option that says location , and select one of the locations from that list, then run your app.

This mock location is the only way to go with simulators.
Let me know if you're having some problems finding it.

**Comment by muslehm** [comment]
Thanks a lot. 
So here's the issue, I have a login page, I login to the map that is supposed to set the marker based on lon and lat variable, but these don't get set. If i go to  next page then back it gets set. 

In another page, where you tweet something, and it fetches your GPS lat/lon, it never gets set up! Never reaches on_location for some reason. It continues using the default lat/lon. I had it set that in the screen class, I define lat and lon (I give it default values), then "on_enter" function, it configures gps. But it never reaches on_location where lat/lon are updated.

**Comment by muslehm** [comment]
Thanks. I figured it out. Apparently it's an issue in the order of placing the code. But now it's sorted thanks.
