### ISSUE TITLE
plyer.notification.notfy() raises NotImplementedError under Python 3.3 in Linux but not Python 2.7

### ISSUE THREAD

**Issue by ghost** [kivy/plyer#58]
Tested  with 1.1.2 under Linux. 

``` python
from kivy.app import App
from plyer import notification

class LinuxApp(App):
    def build(self):
        notification.notify("Title", "Notification")

app = LinuxApp()
app.run()
```

```
 Traceback (most recent call last):
   File "/usr/lib/python3.3/site-packages/plyer/utils.py", line 66, in _ensure_obj
     mod = __import__(module, fromlist='.')
 ImportError: No module named 'plyer.platforms.unknown'
 Traceback (most recent call last):
   File "notify.py", line 9, in <module>
     app.run()
   File "/usr/lib64/python3.3/site-packages/kivy/app.py", line 766, in run
     root = self.build()
   File "notify.py", line 6, in build
     notification.notify("Title", "Notification")
   File "/usr/lib/python3.3/site-packages/plyer/facades.py", line 85, in notify
     self._notify(title=title, message=message)
   File "/usr/lib/python3.3/site-packages/plyer/facades.py", line 90, in _notify
     raise NotImplementedError()
 NotImplementedError
```

**Comment by mahomahomaho** [comment]
I have similar problem with wifi:

```bash
maho@dlaptop:~/workspace/servo/button-kivy$ ipython
Python 2.7.13 (default, Nov 24 2017, 17:33:09)
Type "copyright", "credits" or "license" for more information.

IPython 5.8.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from plyer import wifi

In [2]: wifi
Out[2]: <plyer.platforms.linux.wifi.LinuxWifi at 0x7f3e58713128>

In [3]:                                                                                                                                                                                                                                                                        
Do you really want to exit ([y]/n)? y
(micro-kivy2)
maho@dlaptop:~/workspace/servo/button-kivy$ workon micro-kivy
(micro-kivy)
maho@dlaptop:~/workspace/servo/button-kivy$ ipython
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from plyer import wifi

In [2]: wifi
Out[2]: <plyer.facades.wifi.Wifi at 0x7f851851d288>
```

As you can see, python2 gives LinuxWifi while python3 gives just fascades.wifi.Wifi

**Comment by medram** [comment]
try
pip install wifi
pip install python-wifi
