### ISSUE TITLE
kivy app crashing in mobile on clicking button

### ISSUE THREAD

**Issue by pavankoushal** [kivy/plyer#581]
i have created a kivy app in which we can get list of applications in our mobile and we can uninstall apps in my kivy app .it is working good in pc but, when i install it my mobile it is displaying the list of applications but when i press the delete button of respective app, kivy app is crashing.
 i had also gone through the logcat . it is showing an error  "subprocess.CalledProcessError"

for example i want to delete truecaller app through my kivy app .so when i press the delete button of true caller in kivy app it is showing an error in logact i.e
" subprocess.CalledProcessError: Command 'pm uninstall -k --user 0 com.truecaller ' returned non-zero exit status 255. "
can anybody know what is the error here?   or is there any changes i have to do in my buildozer.spec file ?
i have also tried using different pm commands like "pm uninstall -k com.truecaller" & "su -c pm uninstall -k com.truecaller"
 
pls help me to solve this issue

**Comment by pavankoushal** [comment]
here is my logcat,

08-18 22:05:58.687 26606 26639 I python  : Initializing Python for Android
08-18 22:05:58.687 26606 26639 I python  : Setting additional env vars from p4a_env_vars.txt
08-18 22:05:58.687 26606 26639 I python  : Changing directory to the one provided by ANDROID_ARGUMENT
08-18 22:05:58.687 26606 26639 I python  : /data/user/0/org.ban.bannedapps/files/app
08-18 22:05:58.692 26606 26639 I python  : Preparing to initialize python
08-18 22:05:58.692 26606 26639 I python  : _python_bundle dir exists
08-18 22:05:58.692 26606 26639 I python  : calculated paths to be...
08-18 22:05:58.692 26606 26639 I python  : /data/user/0/org.ban.bannedapps/files/app/_python_bundle/stdlib.zip:/data/user/0/org.ban.bannedapps/files/app/_python_bundle/modules
08-18 22:05:58.710 26606 26639 I python  : set wchar paths...
08-18 22:05:58.768 26606 26639 I python  : Initialized python
08-18 22:05:58.768 26606 26639 I python  : AND: Init threads
08-18 22:05:58.768 26606 26639 I python  : testing python print redirection
08-18 22:05:58.769 26606 26639 I python  : Android path ['.', '/data/user/0/org.ban.bannedapps/files/app/_python_bundle/stdlib.zip', '/data/user/0/org.ban.bannedapps/files/app/_python_bundle/modules', '/data/user/0/org.ban.bannedapps/files/app/_python_bundle/site-packages']
08-18 22:05:58.769 26606 26639 I python  : os.environ is environ({'PATH': '/sbin:/system/sbin:/product/bin:/apex/com.android.runtime/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin', 'ANDROID_BOOTLOGO': '1', 'ANDROID_ROOT': '/system', 'ANDROID_ASSETS': '/system/app', 'ANDROID_DATA': '/data', 'ANDROID_STORAGE': '/storage', 'ANDROID_RUNTIME_ROOT': '/apex/com.android.runtime', 'ANDROID_TZDATA_ROOT': '/apex/com.android.tzdata', 'EXTERNAL_STORAGE': '/sdcard', 'ASEC_MOUNTPOINT': '/mnt/asec', 'BOOTCLASSPATH': '/apex/com.android.runtime/javalib/core-oj.jar:/apex/com.android.runtime/javalib/core-libart.jar:/apex/com.android.runtime/javalib/okhttp.jar:/apex/com.android.runtime/javalib/bouncycastle.jar:/apex/com.android.runtime/javalib/apache-xml.jar:/system/framework/framework.jar:/system/framework/ext.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/android.test.base.jar:/system/framework/oppo-framework.jar:/system/framework/coloros-framework.jar:/system/framework/coloros-support-wrapper.jar:/system/framework/ifaamanager.jar:/system/framework/tcmiface.jar:/system/framework/qcom.fmradio.jar:/system/framework/QPerformance.jar:/system/framework/UxPerformance.jar:/system/framework/telephony-ext.jar:/system/framework/WfdCommon.jar:/apex/com.android.conscrypt/javalib/conscrypt.jar:/apex/com.android.media/javalib/updatable-media.jar', 'DEX2OATBOOTCLASSPATH': '/apex/com.android.runtime/javalib/core-oj.jar:/apex/com.android.runtime/javalib/core-libart.jar:/apex/com.android.runtime/javalib/okhttp.jar:/apex/com.android.runtime/javalib/bouncycastle.jar:/apex/com.android.runtime/javalib/apache-xml.jar:/system/framework/framework.jar:/system/framework/ext.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/android.test.base.jar:/system/framework/oppo-framework.jar:/system/framework/coloros-framework.jar:/system/framework/coloros-support-wrapper.jar:/system/framework/ifaamanager.jar:/system/framework/tcmiface.jar:/system/framework/qcom.fmradio.jar:/system/framework/QPerformance.jar:/system/framework/UxPerformance.jar:/system/framework/telephony-ext.jar:/system/framework/WfdCommon.jar', 'SYSTEMSERVERCLASSPATH': '/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar:/system/framework/com.android.location.provider.jar:/system/framework/coloros-services.jar', 'DOWNLOAD_CACHE': '/data/cache', 'XKIT': '/system/xbin/xkit_10', 'ANDROID_SOCKET_zygote_secondary': '19', 'ANDROID_SOCKET_usap_pool_secondary': '20', 'ANDROID_ENTRYPOINT': 'main.pyc', 'ANDROID_ARGUMENT': '/data/user/0/org.ban.bannedapps/files/app', 'ANDROID_APP_PATH': '/data/user/0/org.ban.bannedapps/files/app', 'ANDROID_PRIVATE': '/data/user/0/org.ban.bannedapps/files', 'ANDROID_UNPACK': '/data/user/0/org.ban.bannedapps/files/app', 'PYTHONHOME': '/data/user/0/org.ban.bannedapps/files/app', 'PYTHONPATH': '/data/user/0/org.ban.bannedapps/files/app:/data/user/0/org.ban.bannedapps/files/app/lib', 'PYTHONOPTIMIZE': '2', 'P4A_BOOTSTRAP': 'SDL2', 'PYTHON_NAME': 'python', 'P4A_IS_WINDOWED': 'True', 'P4A_ORIENTATION': 'portrait', 'P4A_NUMERIC_VERSION': 'None', 'P4A_MINSDK': '21', 'LC_CTYPE': 'C.UTF-8'})
08-18 22:05:58.769 26606 26639 I python  : Android kivy bootstrap done. __name__ is __main__
08-18 22:05:58.769 26606 26639 I python  : AND: Ran string
08-18 22:05:58.769 26606 26639 I python  : Run user program, change dir and execute entrypoint
08-18 22:05:58.864 26606 26639 I python  : [WARNING] [Config      ] Older configuration version detected (0 instead of 21)
08-18 22:05:58.864 26606 26639 I python  : [WARNING] [Config      ] Upgrading configuration in progress.
08-18 22:05:58.870 26606 26639 I python  : [INFO   ] [Logger      ] Record log in /data/user/0/org.ban.bannedapps/files/app/.kivy/logs/kivy_20-08-18_0.txt
08-18 22:05:58.870 26606 26639 I python  : [INFO   ] [Kivy        ] v1.11.1
08-18 22:05:58.870 26606 26639 I python  : [INFO   ] [Kivy        ] Installed at "/data/user/0/org.ban.bannedapps/files/app/_python_bundle/site-packages/kivy/__init__.pyc"
08-18 22:05:58.870 26606 26639 I python  : [INFO   ] [Python      ] v3.8.1 (default, Jul 22 2020, 21:52:51) 
08-18 22:05:58.870 26606 26639 I python  : [Clang 8.0.2 (https://android.googlesource.com/toolchain/clang 40173bab62ec7462
08-18 22:05:58.870 26606 26639 I python  : [INFO   ] [Python      ] Interpreter at ""
08-18 22:05:59.455 26606 26639 I python  : [INFO   ] [Factory     ] 184 symbols loaded
08-18 22:05:59.683 26606 26639 I python  : [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
08-18 22:05:59.718 26606 26639 I python  : [INFO   ] [Text        ] Provider: sdl2
08-18 22:05:59.771 26606 26639 I python  : [INFO   ] [Window      ] Provider: sdl2
08-18 22:05:59.796 26606 26639 I python  : [INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
08-18 22:05:59.797 26606 26639 I python  : [INFO   ] [GL          ] Backend used <sdl2>
08-18 22:05:59.797 26606 26639 I python  : [INFO   ] [GL          ] OpenGL version <b'OpenGL ES 3.2 V@415.0 (GIT@e4029f9, I6b4cbc7431, 1569964966) (Date:10/01/19)'>
08-18 22:05:59.798 26606 26639 I python  : [INFO   ] [GL          ] OpenGL vendor <b'Qualcomm'>
08-18 22:05:59.798 26606 26639 I python  : [INFO   ] [GL          ] OpenGL renderer <b'Adreno (TM) 616'>
08-18 22:05:59.798 26606 26639 I python  : [INFO   ] [GL          ] OpenGL parsed version: 3, 2
08-18 22:05:59.798 26606 26639 I python  : [INFO   ] [GL          ] Texture max size <16384>
08-18 22:05:59.798 26606 26639 I python  : [INFO   ] [GL          ] Texture max units <16>
08-18 22:05:59.814 26606 26639 I python  : [INFO   ] [Window      ] auto add sdl2 input provider
08-18 22:05:59.815 26606 26639 I python  : [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
08-18 22:06:02.163 26606 26639 I python  :    File "/home/koushal/PycharmProjects/my_app2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/bannedapps/kivy/uix/scrollview.py", line 895, in on_touch_up
08-18 22:06:02.164 26606 26639 I python  :    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
08-18 22:06:02.164 26606 26639 I python  :    File "/home/koushal/PycharmProjects/my_app2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/bannedapps/kivy/uix/scrollview.py", line 934, in on_scroll_stop
08-18 22:06:02.165 26606 26639 I python  :    File "/home/koushal/PycharmProjects/my_app2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/bannedapps/kivy/uix/scrollview.py", line 642, in simulate_touch_down
08-18 22:06:02.165 26606 26639 I python  :    File "/home/koushal/PycharmProjects/my_app2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/bannedapps/kivy/uix/widget.py", line 549, in on_touch_down
08-18 22:06:02.166 26606 26639 I python  :    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
08-18 22:06:02.166 26606 26639 I python  :    File "/home/koushal/PycharmProjects/my_app2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/bannedapps/kivy/uix/widget.py", line 549, in on_touch_down
08-18 22:06:02.167 26606 26639 I python  :    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
08-18 22:06:02.167 26606 26639 I python  :    File "/home/koushal/PycharmProjects/my_app2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/bannedapps/kivy/uix/behaviors/button.py", line 151, in on_touch_down
08-18 22:06:02.168 26606 26639 I python  :    File "kivy/_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
08-18 22:06:02.168 26606 26639 I python  :    File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
08-18 22:06:02.169 26606 26639 I python  :    File "kivy/_event.pyx", line 1138, in kivy._event.EventObservers._dispatch
08-18 22:06:02.169 26606 26639 I python  :    File "/home/koushal/PycharmProjects/my_app2/.buildozer/android/app/main.py", line 133, in callback
08-18 22:06:02.170 26606 26639 I python  :    File "/home/koushal/PycharmProjects/my_app2/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/subprocess.py", line 411, in check_output
08-18 22:06:02.170 26606 26639 I python  :    File "/home/koushal/PycharmProjects/my_app2/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/subprocess.py", line 512, in run
08-18 22:06:02.171 26606 26639 I python  :  subprocess.CalledProcessError: Command 'pm uninstall -k com.twitter.android' returned non-zero exit status 255.
08-18 22:06:02.171 26606 26639 I python  : Python for android ended.

**Comment by pavankoushal** [comment]
here is my logcat,
08-18 00:25:56.010  3834  3867 I python  : Initializing Python for Android
08-18 00:25:56.010  3834  3867 I python  : Setting additional env vars from p4a_env_vars.txt
08-18 00:25:56.014  3834  3867 I python  : Changing directory to the one provided by ANDROID_ARGUMENT
08-18 00:25:56.014  3834  3867 I python  : /data/user/0/org.ban.bannedapps/files/app
08-18 00:25:56.017  3834  3867 I python  : Preparing to initialize python
08-18 00:25:56.017  3834  3867 I python  : _python_bundle dir exists
08-18 00:25:56.017  3834  3867 I python  : calculated paths to be...
08-18 00:25:56.017  3834  3867 I python  : /data/user/0/org.ban.bannedapps/files/app/_python_bundle/stdlib.zip:/data/user/0/org.ban.bannedapps/files/app/_python_bundle/modules
08-18 00:25:56.023  3834  3867 I python  : set wchar paths...
08-18 00:25:56.087  3834  3867 I python  : Initialized python
08-18 00:25:56.087  3834  3867 I python  : AND: Init threads
08-18 00:25:56.087  3834  3867 I python  : testing python print redirection
08-18 00:25:56.088  3834  3867 I python  : Android path ['.', '/data/user/0/org.ban.bannedapps/files/app/_python_bundle/stdlib.zip', '/data/user/0/org.ban.bannedapps/files/app/_python_bundle/modules', '/data/user/0/org.ban.bannedapps/files/app/_python_bundle/site-packages']
08-18 00:25:56.088  3834  3867 I python  : os.environ is environ({'PATH': '/sbin:/system/sbin:/product/bin:/apex/com.android.runtime/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin', 'ANDROID_BOOTLOGO': '1', 'ANDROID_ROOT': '/system', 'ANDROID_ASSETS': '/system/app', 'ANDROID_DATA': '/data', 'ANDROID_STORAGE': '/storage', 'ANDROID_RUNTIME_ROOT': '/apex/com.android.runtime', 'ANDROID_TZDATA_ROOT': '/apex/com.android.tzdata', 'EXTERNAL_STORAGE': '/sdcard', 'ASEC_MOUNTPOINT': '/mnt/asec', 'BOOTCLASSPATH': '/apex/com.android.runtime/javalib/core-oj.jar:/apex/com.android.runtime/javalib/core-libart.jar:/apex/com.android.runtime/javalib/okhttp.jar:/apex/com.android.runtime/javalib/bouncycastle.jar:/apex/com.android.runtime/javalib/apache-xml.jar:/system/framework/framework.jar:/system/framework/ext.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/android.test.base.jar:/system/framework/oppo-framework.jar:/system/framework/coloros-framework.jar:/system/framework/coloros-support-wrapper.jar:/system/framework/ifaamanager.jar:/system/framework/tcmiface.jar:/system/framework/qcom.fmradio.jar:/system/framework/QPerformance.jar:/system/framework/UxPerformance.jar:/system/framework/telephony-ext.jar:/system/framework/WfdCommon.jar:/apex/com.android.conscrypt/javalib/conscrypt.jar:/apex/com.android.media/javalib/updatable-media.jar', 'DEX2OATBOOTCLASSPATH': '/apex/com.android.runtime/javalib/core-oj.jar:/apex/com.android.runtime/javalib/core-libart.jar:/apex/com.android.runtime/javalib/okhttp.jar:/apex/com.android.runtime/javalib/bouncycastle.jar:/apex/com.android.runtime/javalib/apache-xml.jar:/system/framework/framework.jar:/system/framework/ext.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/android.test.base.jar:/system/framework/oppo-framework.jar:/system/framework/coloros-framework.jar:/system/framework/coloros-support-wrapper.jar:/system/framework/ifaamanager.jar:/system/framework/tcmiface.jar:/system/framework/qcom.fmradio.jar:/system/framework/QPerformance.jar:/system/framework/UxPerformance.jar:/system/framework/telephony-ext.jar:/system/framework/WfdCommon.jar', 'SYSTEMSERVERCLASSPATH': '/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar:/system/framework/com.android.location.provider.jar:/system/framework/coloros-services.jar', 'DOWNLOAD_CACHE': '/data/cache', 'XKIT': '/system/xbin/xkit_10', 'ANDROID_SOCKET_zygote_secondary': '19', 'ANDROID_SOCKET_usap_pool_secondary': '20', 'ANDROID_ENTRYPOINT': 'main.pyc', 'ANDROID_ARGUMENT': '/data/user/0/org.ban.bannedapps/files/app', 'ANDROID_APP_PATH': '/data/user/0/org.ban.bannedapps/files/app', 'ANDROID_PRIVATE': '/data/user/0/org.ban.bannedapps/files', 'ANDROID_UNPACK': '/data/user/0/org.ban.bannedapps/files/app', 'PYTHONHOME': '/data/user/0/org.ban.bannedapps/files/app', 'PYTHONPATH': '/data/user/0/org.ban.bannedapps/files/app:/data/user/0/org.ban.bannedapps/files/app/lib', 'PYTHONOPTIMIZE': '2', 'P4A_BOOTSTRAP': 'SDL2', 'PYTHON_NAME': 'python', 'P4A_IS_WINDOWED': 'True', 'P4A_ORIENTATION': 'portrait', 'P4A_NUMERIC_VERSION': 'None', 'P4A_MINSDK': '21', 'LC_CTYPE': 'C.UTF-8'})
08-18 00:25:56.088  3834  3867 I python  : Android kivy bootstrap done. __name__ is __main__
08-18 00:25:56.088  3834  3867 I python  : AND: Ran string
08-18 00:25:56.088  3834  3867 I python  : Run user program, change dir and execute entrypoint
08-18 00:25:56.244  3834  3867 I python  : [INFO   ] [Logger      ] Record log in /data/user/0/org.ban.bannedapps/files/app/.kivy/logs/kivy_20-08-18_0.txt
08-18 00:25:56.244  3834  3867 I python  : [INFO   ] [Kivy        ] v1.11.1
08-18 00:25:56.244  3834  3867 I python  : [INFO   ] [Kivy        ] Installed at "/data/user/0/org.ban.bannedapps/files/app/_python_bundle/site-packages/kivy/__init__.pyc"
08-18 00:25:56.244  3834  3867 I python  : [INFO   ] [Python      ] v3.8.1 (default, Jul 22 2020, 21:52:51) 
08-18 00:25:56.244  3834  3867 I python  : [Clang 8.0.2 (https://android.googlesource.com/toolchain/clang 40173bab62ec7462
08-18 00:25:56.244  3834  3867 I python  : [INFO   ] [Python      ] Interpreter at ""
08-18 00:25:56.833  3834  3867 I python  : [INFO   ] [Factory     ] 184 symbols loaded
08-18 00:25:57.107  3834  3867 I python  : [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
08-18 00:25:57.166  3834  3867 I python  : [INFO   ] [Text        ] Provider: sdl2
08-18 00:25:57.291  3834  3867 I python  : [INFO   ] [Window      ] Provider: sdl2
08-18 00:25:57.323  3834  3867 I python  : [INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
08-18 00:25:57.324  3834  3867 I python  : [INFO   ] [GL          ] Backend used <sdl2>
08-18 00:25:57.325  3834  3867 I python  : [INFO   ] [GL          ] OpenGL version <b'OpenGL ES 3.2 V@415.0 (GIT@e4029f9, I6b4cbc7431, 1569964966) (Date:10/01/19)'>
08-18 00:25:57.325  3834  3867 I python  : [INFO   ] [GL          ] OpenGL vendor <b'Qualcomm'>
08-18 00:25:57.325  3834  3867 I python  : [INFO   ] [GL          ] OpenGL renderer <b'Adreno (TM) 616'>
08-18 00:25:57.325  3834  3867 I python  : [INFO   ] [GL          ] OpenGL parsed version: 3, 2
08-18 00:25:57.325  3834  3867 I python  : [INFO   ] [GL          ] Texture max size <16384>
08-18 00:25:57.325  3834  3867 I python  : [INFO   ] [GL          ] Texture max units <16>
08-18 00:25:57.333  3834  3867 I python  : [INFO   ] [Window      ] auto add sdl2 input provider
08-18 00:25:57.336  3834  3867 I python  : [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
08-18 00:25:57.472  3834  3867 I python  : (1080, 2258)
08-18 00:25:57.472  3834  3867 I python  : 2258 1080
08-18 00:25:57.546  3834  3867 I python  : package:com.intsig.camscanner
08-18 00:25:57.549  3834  3867 I python  : package:com.google.android.apps.nbu.paisa.user
08-18 00:25:57.551  3834  3867 I python  : package:com.adobe.lrmobile
08-18 00:25:57.553  3834  3867 I python  : package:com.realmestore.app
08-18 00:25:57.554  3834  3867 I python  : package:org.telegram.messenger
08-18 00:25:57.559  3834  3867 I python  : package:com.phonepe.app
08-18 00:25:57.561  3834  3867 I python  : package:com.niksoftware.snapseed
08-18 00:25:57.563  3834  3867 I python  : package:com.microsoft.office.excel
08-18 00:25:57.565  3834  3867 I python  : package:in.amazon.mShop.android.shopping
08-18 00:25:57.567  3834  3867 I python  : package:com.flipkart.android
08-18 00:25:57.569  3834  3867 I python  : package:com.instagram.android
08-18 00:25:57.571  3834  3867 I python  : package:in.startv.hotstar
08-18 00:25:57.573  3834  3867 I python  : package:com.mxtech.videoplayer.ad
08-18 00:25:57.575  3834  3867 I python  : package:com.twitter.android
08-18 00:25:57.583  3834  3867 I python  : [WARNING] [Base        ] Unknown <android> provider
08-18 00:25:57.583  3834  3867 I python  : [INFO   ] [Base        ] Start application main loop
08-18 00:25:57.589  3834  3867 I python  : [INFO   ] [GL          ] NPOT texture support is available
08-18 00:27:19.920  3834  3867 I python  : ('package:com.twitter.android', <kivy.uix.button.Button object at 0xbdb2a358>)
08-18 00:27:19.920  3834  3867 I python  : pm uninstall -k --user 0 com.twitter.android
08-18 00:27:20.079  3834  3867 I python  : [INFO   ] [Base        ] Leaving application in progress...
08-18 00:27:20.080  3834  3867 I python  :  Traceback (most recent call last):
08-18 00:27:20.081  3834  3867 I python  :    File "/home/koushal/PycharmProjects/my_app2/.buildozer/android/app/main.py", line 156, in <module>
08-18 00:27:20.082  3834  3867 I python  :    File "/home/koushal/PycharmProjects/my_app2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/bannedapps/kivy/app.py", line 855, in run
08-18 00:27:20.083  3834  3867 I python  :    File "/home/koushal/PycharmProjects/my_app2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/bannedapps/kivy/base.py", line 504, in runTouchApp
08-18 00:27:20.084  3834  3867 I python  :    File "/home/koushal/PycharmProjects/my_app2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/bannedapps/kivy/core/window/window_sdl2.py", line 747, in mainloop
08-18 00:27:20.084  3834  3867 I python  :    File "/home/koushal/PycharmProjects/my_app2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/bannedapps/kivy/core/window/window_sdl2.py", line 479, in _mainloop
08-18 00:27:20.085  3834  3867 I python  :    File "/home/koushal/PycharmProjects/my_app2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/bannedapps/kivy/base.py", line 342, in idle
08-18 00:27:20.086  3834  3867 I python  :    File "/home/koushal/PycharmProjects/my_app2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/bannedapps/kivy/base.py", line 327, in dispatch_input
08-18 00:27:20.087  3834  3867 I python  :    File "/home/koushal/PycharmProjects/my_app2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/bannedapps/kivy/base.py", line 233, in post_dispatch_input
08-18 00:27:20.087  3834  3867 I python  :    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
08-18 00:27:20.088  3834  3867 I python  :    File "/home/koushal/PycharmProjects/my_app2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/bannedapps/kivy/core/window/__init__.py", line 1406, in on_motion
08-18 00:27:20.089  3834  3867 I python  :    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
08-18 00:27:20.090  3834  3867 I python  :    File "/home/koushal/PycharmProjects/my_app2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/bannedapps/kivy/core/window/__init__.py", line 1442, in on_touch_up
08-18 00:27:20.090  3834  3867 I python  :    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
08-18 00:27:20.091  3834  3867 I python  :    File "/home/koushal/PycharmProjects/my_app2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/bannedapps/kivy/uix/widget.py", line 571, in on_touch_up
08-18 00:27:20.092  3834  3867 I python  :    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
08-18 00:27:20.093  3834  3867 I python  :    File "/home/koushal/PycharmProjects/my_app2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/bannedapps/kivy/uix/scrollview.py", line 895, in on_touch_up
08-18 00:27:20.093  3834  3867 I python  :    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
08-18 00:27:20.094  3834  3867 I python  :    File "/home/koushal/PycharmProjects/my_app2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/bannedapps/kivy/uix/scrollview.py", line 934, in on_scroll_stop
08-18 00:27:20.095  3834  3867 I python  :    File "/home/koushal/PycharmProjects/my_app2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/bannedapps/kivy/uix/scrollview.py", line 642, in simulate_touch_down
08-18 00:27:20.096  3834  3867 I python  :    File "/home/koushal/PycharmProjects/my_app2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/bannedapps/kivy/uix/widget.py", line 549, in on_touch_down
08-18 00:27:20.096  3834  3867 I python  :    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
08-18 00:27:20.097  3834  3867 I python  :    File "/home/koushal/PycharmProjects/my_app2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/bannedapps/kivy/uix/widget.py", line 549, in on_touch_down
08-18 00:27:20.098  3834  3867 I python  :    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
08-18 00:27:20.098  3834  3867 I python  :    File "/home/koushal/PycharmProjects/my_app2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/bannedapps/kivy/uix/behaviors/button.py", line 151, in on_touch_down
08-18 00:27:20.099  3834  3867 I python  :    File "kivy/_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
08-18 00:27:20.100  3834  3867 I python  :    File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
08-18 00:27:20.100  3834  3867 I python  :    File "kivy/_event.pyx", line 1138, in kivy._event.EventObservers._dispatch
08-18 00:27:20.101  3834  3867 I python  :    File "/home/koushal/PycharmProjects/my_app2/.buildozer/android/app/main.py", line 146, in callback
08-18 00:27:20.102  3834  3867 I python  :    File "/home/koushal/PycharmProjects/my_app2/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/subprocess.py", line 411, in check_output
08-18 00:27:20.103  3834  3867 I python  :    File "/home/koushal/PycharmProjects/my_app2/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/subprocess.py", line 512, in run
08-18 00:27:20.104  3834  3867 I python  :  subprocess.CalledProcessError: Command 'pm uninstall -k --user 0 com.twitter.android' returned non-zero exit status 255.
08-18 00:27:20.104  3834  3867 I python  : Python for android ended.
