### ISSUE TITLE
Speech Recognition on Android Crash

### ISSUE THREAD

**Issue by dimitar-petrov** [kivy/plyer#583]
Hello,

I am trying to test the following example: https://github.com/kivy/plyer/tree/master/examples/speech2text 
I have deployed the app with buildozer and allowed both mic and storage permissions on the phone, but I get the following exception.

Can someone elaborate what might be the cause please.

```
09-09 00:23:54.874  1533  2025 I chatty  : uid=1000(system) SensorService identical 6 lines
09-09 00:23:55.130  1533  2025 D SensorService: FusionLight, after outEvent->light = 0.000000[LB]
09-09 00:23:55.221  4453  4453 D TouchInteractionService: onInputEvent# ev: MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=575.0, y[0]=2026.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=38270923, downTime=38270923, deviceId=8, source=0x1002, displayId=0 }
09-09 00:23:55.315   926  7374 I /vendor/bin/hw/vendor.qti.hardware.servicetracker@1.0-service: bindService is called for service : com.google.android.googlequicksearchbox/com.google.android.voicesearch.serviceapi.GoogleRecognitionService and for client org.test.plyer.speech.recognition
09-09 00:23:55.315   926  7374 I /vendor/bin/hw/vendor.qti.hardware.servicetracker@1.0-service: total connections for service : com.google.android.googlequicksearchbox/com.google.android.voicesearch.serviceapi.GoogleRecognitionServiceare :1
09-09 00:23:55.315   926  7374 I /vendor/bin/hw/vendor.qti.hardware.servicetracker@1.0-service: total connections for client : org.test.plyer.speech.recognitionare :1
09-09 00:23:55.327   926  7374 I /vendor/bin/hw/vendor.qti.hardware.servicetracker@1.0-service: startService() is called for servicecom.google.android.googlequicksearchbox/com.google.android.voicesearch.serviceapi.GoogleRecognitionService
09-09 00:23:55.332  6641  6641 W Bundle  : Key android.speech.extra.MAX_RESULTS expected Integer but value was a java.lang.Short.  The default value 1 was returned.
09-09 00:23:55.332  6641  6641 W Bundle  : Attempt to cast generated internal exception:
09-09 00:23:55.332  6641  6641 W Bundle  : java.lang.ClassCastException: java.lang.Short cannot be cast to java.lang.Integer
09-09 00:23:55.332  6641  6641 W Bundle  :      at android.os.BaseBundle.getInt(BaseBundle.java:1046)
09-09 00:23:55.332  6641  6641 W Bundle  :      at android.content.Intent.getIntExtra(Intent.java:7851)
09-09 00:23:55.332  6641  6641 W Bundle  :      at com.google.android.apps.search.transcription.f.w.d(SourceFile:39)
09-09 00:23:55.332  6641  6641 W Bundle  :      at com.google.android.apps.search.transcription.f.e.v.a(SourceFile:32)
09-09 00:23:55.332  6641  6641 W Bundle  :      at com.google.android.voicesearch.serviceapi.GoogleRecognitionService.onStartListening(SourceFile:47)
09-09 00:23:55.332  6641  6641 W Bundle  :      at android.speech.RecognitionService.dispatchStartListening(RecognitionService.java:113)
09-09 00:23:55.332  6641  6641 W Bundle  :      at android.speech.RecognitionService.access$000(RecognitionService.java:39)
09-09 00:23:55.332  6641  6641 W Bundle  :      at android.speech.RecognitionService$1.handleMessage(RecognitionService.java:82)
09-09 00:23:55.332  6641  6641 W Bundle  :      at android.os.Handler.dispatchMessage(Handler.java:107)
09-09 00:23:55.332  6641  6641 W Bundle  :      at android.os.Looper.loop(Looper.java:214)
09-09 00:23:55.332  6641  6641 W Bundle  :      at android.app.ActivityThread.main(ActivityThread.java:7710)
09-09 00:23:55.332  6641  6641 W Bundle  :      at java.lang.reflect.Method.invoke(Native Method)
09-09 00:23:55.332  6641  6641 W Bundle  :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
09-09 00:23:55.332  6641  6641 W Bundle  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
09-09 00:23:55.332  6641  6641 I w       : Using Locale.getDefault() for recognition: null
09-09 00:23:55.333  6641  6641 E k       : Error parsing intent: EXTRA_PREFER_OFFLINE parameter is deprecated.
09-09 00:23:55.339   926  7374 I /vendor/bin/hw/vendor.qti.hardware.servicetracker@1.0-service: unbindService is called for service : com.google.android.googlequicksearchbox/com.google.android.voicesearch.serviceapi.GoogleRecognitionService and for client org.test.plyer.speech.recognition
09-09 00:23:55.339   926  7374 I /vendor/bin/hw/vendor.qti.hardware.servicetracker@1.0-service: size of service connections for service: com.google.android.googlequicksearchbox/com.google.android.voicesearch.serviceapi.GoogleRecognitionServiceafter removal is 0
09-09 00:23:55.339   926  7374 I /vendor/bin/hw/vendor.qti.hardware.servicetracker@1.0-service: size of client connections for client: org.test.plyer.speech.recognitionafter removal is 0
09-09 00:23:55.340  6641 13716 W Binder  : Caught a RuntimeException from the binder stub implementation.
09-09 00:23:55.340  6641 13716 W Binder  : java.lang.SecurityException: uid 10204 does not have android.permission.UPDATE_APP_OPS_STATS.
09-09 00:23:55.340  6641 13716 W Binder  :      at android.os.Parcel.createException(Parcel.java:2071)
09-09 00:23:55.340  6641 13716 W Binder  :      at android.os.Parcel.readException(Parcel.java:2039)
09-09 00:23:55.340  6641 13716 W Binder  :      at android.os.Parcel.readException(Parcel.java:1987)
09-09 00:23:55.340  6641 13716 W Binder  :      at com.android.internal.app.IAppOpsService$Stub$Proxy.checkOperationRaw(IAppOpsService.java:1617)
09-09 00:23:55.340  6641 13716 W Binder  :      at android.app.AppOpsManager.unsafeCheckOpRawNoThrow(AppOpsManager.java:5116)
09-09 00:23:55.340  6641 13716 W Binder  :      at android.content.PermissionChecker.checkPermissionCommon(PermissionChecker.java:403)
09-09 00:23:55.340  6641 13716 W Binder  :      at android.content.PermissionChecker.checkPermissionForPreflight(PermissionChecker.java:162)
09-09 00:23:55.340  6641 13716 W Binder  :      at android.content.PermissionChecker.checkCallingOrSelfPermissionForPreflight(PermissionChecker.java:373)
09-09 00:23:55.340  6641 13716 W Binder  :      at android.speech.RecognitionService.checkPermissions(RecognitionService.java:185)
09-09 00:23:55.340  6641 13716 W Binder  :      at android.speech.RecognitionService.access$700(RecognitionService.java:39)
09-09 00:23:55.340  6641 13716 W Binder  :      at android.speech.RecognitionService$RecognitionServiceBinder.cancel(RecognitionService.java:376)
09-09 00:23:55.340  6641 13716 W Binder  :      at android.speech.IRecognitionService$Stub.onTransact(IRecognitionService.java:149)
09-09 00:23:55.340  6641 13716 W Binder  :      at android.os.Binder.execTransactInternal(Binder.java:1032)
09-09 00:23:55.340  6641 13716 W Binder  :      at android.os.Binder.execTransact(Binder.java:1005)
09-09 00:23:55.340  6641 13716 W Binder  : Caused by: android.os.RemoteException: Remote stack trace:
09-09 00:23:55.340  6641 13716 W Binder  :      at android.app.ContextImpl.enforce(ContextImpl.java:1930)
09-09 00:23:55.340  6641 13716 W Binder  :      at android.app.ContextImpl.enforcePermission(ContextImpl.java:1939)
09-09 00:23:55.340  6641 13716 W Binder  :      at com.android.server.appop.AppOpsService.verifyIncomingUid(AppOpsService.java:2532)
09-09 00:23:55.340  6641 13716 W Binder  :      at com.android.server.appop.AppOpsService.checkOperationImpl(AppOpsService.java:1846)
09-09 00:23:55.340  6641 13716 W Binder  :      at com.android.server.appop.AppOpsService.checkOperationInternal(AppOpsService.java:1838)
09-09 00:23:55.340  6641 13716 W Binder  : 
09-09 00:23:55.340   926  7374 I /vendor/bin/hw/vendor.qti.hardware.servicetracker@1.0-service: destroyService is called for service : com.google.android.googlequicksearchbox/com.google.android.voicesearch.serviceapi.GoogleRecognitionService
09-09 00:23:55.341  6641  6641 I k       : #onDestroy
09-09 00:23:55.345 26594 26594 E SpeechRecognizer: not connected to the recognition service
09-09 00:23:55.394  1533  2025 D SensorService: FusionLight, after outEvent->light = 0.000000[LB]
```

**Comment by ignamendi21** [comment]
did you solve it?
