### ISSUE TITLE
Macox notification - AttributeError: 'NoneType' object has no attribute 'setDelegate_'

### ISSUE THREAD

**Issue by wwj718** [kivy/plyer#586]
Python == 3.7.2
MacOS 10.13.5
Plyer == 1.4.3
PyInstaller == 3.6

After I packed file with PyInstaller I got following error when I run notify.

Traceback (most recent call last): 

```
 File "plyer/facades/notification.py", line 84, in notify
  File "plyer/platforms/macosx/notification.py", line 46, in _notify
AttributeError: 'NoneType' object has no attribute 'setDelegate_'

```

and I had added `"plyer.platforms.macosx.notification"` to hiddenimports

**Comment by 0xSEM** [comment]
I'm facing this same issue on Python 3.9 after packing my app with PyInstaller, can you elaborate how you've fixed this? @wwj718

**Comment by 0xSEM** [comment]
#551 This actually fixed the issue for me.

The existing implementation seems to work fine, but once packed with PyInstaller the default implementation returns a NoneType for 'NSUserNotificationCenter' (which according to Apple is also deprecated https://developer.apple.com/documentation/foundation/nsusernotificationcenter)

**Comment by inspectorG4dget** [comment]
I now face this issue on Mac OS X 13.5.2 (Ventura) with python 3.9.7. Installed via `pip`

I didn't really need a callback, so I tried this
```
import sqlite3
import functools

from bpylist import bplist
from mac_notifications import client

if __name__ == "__main__":
    client.create_notification(title='Notification title', subtitle="notification subtitle", icon="calendar.png")
```
and got this error

```
$ python main.py
Process NotificationProcess-1:
Traceback (most recent call last):
  File "/.../.pyenv/versions/3.9.7/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/.../.venv/lib/python3.9/site-packages/mac_notifications/listener_process.py", line 28, in run
    notification_sender.create_notification(self.notification_config, self.queue).send()
  File "/.../.venv/lib/python3.9/site-packages/mac_notifications/notification_sender.py", line 58, in send
    NSUserNotificationCenter.defaultUserNotificationCenter().setDelegate_(self)
AttributeError: 'NoneType' object has no attribute 'setDelegate_'
```

So, thinking a callback is necessary, I tried this

```
import sqlite3
import functools

from bpylist import bplist
from mac_notifications import client

if __name__ == "__main__":

    client.create_notification(title = 'Notification title',
                               subtitle = "notification subtitle",
                               icon = "calendar.png",
                               action_callback = functools.partial(lambda *args:None,  # dummy callback. It does nothing
                                                                   1,
                                                                   ),
                               )
```
and still got this error
```
$ python main.py
Process NotificationProcess-1:
Traceback (most recent call last):
  File "/.../.pyenv/versions/3.9.7/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/.../.venv/lib/python3.9/site-packages/mac_notifications/listener_process.py", line 28, in run
    notification_sender.create_notification(self.notification_config, self.queue).send()
  File "/.../.venv/lib/python3.9/site-packages/mac_notifications/notification_sender.py", line 58, in send
    NSUserNotificationCenter.defaultUserNotificationCenter().setDelegate_(self)
AttributeError: 'NoneType' object has no attribute 'setDelegate_'
```

I'd appreciate any help

**Comment by blazing-gig** [comment]
The issue occurs even without PyInstaller with the below spec:

Python: 3.10
MacOS Monterey: 12.7
Plyer: 2.1.0

I believe #551 fixes the problem. +1 for getting it merged in the main trunk.
