### ISSUE TITLE
Notification not working on macos

### ISSUE THREAD

**Issue by kostino** [kivy/plyer#593]
Traceback (most recent call last):
  File "...../python3.7/site-packages/plyer/utils.py", line 93, in _ensure_obj
    mod = __import__(module, fromlist='.')
  File "...../python3.7/site-packages/plyer/platforms/macosx/notification.py", line 7, in <module>
    from pyobjus import (
ModuleNotFoundError: No module named 'pyobjus'
Ignoring exception in command notification:
Traceback (most recent call last):
  File "...../lib/helpers.py", line 26, in run
    return await f(*args,**kwargs)
  File ".....pyw", line 206, in notification
    await notification_module.notification(ctx, txt)
  File "....../modules/notification_module.py", line 16, in notification
    timeout=999999)
  File "..../python3.7/site-packages/plyer/facades/notification.py", line 82, in notify
    timeout=timeout, ticker=ticker, toast=toast
  File "..../python3.7/site-packages/plyer/facades/notification.py", line 88, in _notify
    raise NotImplementedError("No usable implementation found!")
NotImplementedError: No usable implementation found!

It seems that for some reason it calls the facade code on macosx
The platform is recognised as plyer.utils.platform returns macosx

**Comment by themindstorm** [comment]
I was facing the same issue and I use this package aquaui which has working notifications

https://github.com/ninest/aquaui

**Comment by Mkhuphy** [comment]
Try:  "pip3 install pyobjus"

**Comment by devAbreu** [comment]
> Try: "pip3 install pyobjus"
I was getting the same error. And installing pyobjus, the error was gone.
