### ISSUE TITLE
cannot generate a notification on python. i am getting the error given below

### ISSUE THREAD

**Issue by Rupanwita** [kivy/plyer#598]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/plyer/utils.py", line 93, in _ensure_obj
    mod = __import__(module, fromlist='.')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/plyer/platforms/macosx/notification.py", line 7, in <module>
    from pyobjus import (
ModuleNotFoundError: No module named 'pyobjus'
Traceback (most recent call last):
  File "/Users/rupanwita/Desktop/desktop_sun_notification.py", line 5, in <module>
    notification.notify(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/plyer/facades/notification.py", line 79, in notify
    self._notify(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/plyer/facades/notification.py", line 88, in _notify
    raise NotImplementedError("No usable implementation found!")
NotImplementedError: No usable implementation found!

**Comment by Ratulhasan14789** [comment]
which os are you using? works fine on windows and linux

**Comment by Rupanwita** [comment]
> which os are you using? works fine on windows and linux for me

ios

**Comment by vegardjervell** [comment]
I have the same issue with the exact same error. Running python 3.9.12 on MacOS 10.14.6 (I know, it's old, that may be the problem)

**Comment by HyTurtle** [comment]
Original issue here would appear to be the **pyobjus** lib was missing

**Comment by vegardjervell** [comment]
Sure enough, it worked out after installing `pyobjus` :) shouldn't that be handled by `setup.py` though?

**Comment by HyTurtle** [comment]
Don't have much knowledge on ios/toolchain... as per android though; I'd say it shouldn't be handled by setup.py, but based on the plyer recipe it should be doing so there already.
