### ISSUE TITLE
Exception: Shell_NotifyIconW failed occurs after some time

### ISSUE THREAD

**Issue by keck-in-space** [kivy/plyer#645]
After some amount of notifications, the following occurs.

```bash
Traceback (most recent call last):
  File "C:\<snip>\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\<snip>\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\<snip>\lib\site-packages\plyer\platforms\win\libs\balloontip.py", line 206, in balloon_tip
    WindowsBalloonTip(**kwargs)
  File "C:\<snip>\lib\site-packages\plyer\platforms\win\libs\balloontip.py", line 139, in __init__
    self.notify(title, message, app_name)
  File "C:\<snip>\lib\site-packages\plyer\platforms\win\libs\balloontip.py", line 188, in notify
    raise Exception('Shell_NotifyIconW failed.')
Exception: Shell_NotifyIconW failed.
```

The only fix I know of is to logout and back in. Any other ideas?

Windows 10
Python 3.9.7
Plyer 2.0.0

**Comment by SantiiRepair** [comment]
Kivy's wonderful team ignored you, lol
