### ISSUE TITLE
FileChooser raises NotImplementedError/ModuleNotFoundError without pywin32 on windows 10

### ISSUE THREAD

**Issue by nWestie** [kivy/plyer#735]
When using plyer FileChooser without kivy, it raises an error when it cannot find the win32 module. After installing pywin32, it works fine. Could pywin32 be added as a dependancy of plyer, to reduce confusion? Kivy installs it automatically on windows.
See also: #602
the full error/traceback:

> Traceback (most recent call last):
  File "C:\Users\<USER>\scripts\.venv\lib\site-packages\plyer\utils.py", line 96, in _ensure_obj
    mod = __import__(module, fromlist='.')
    from win32com.shell.shell import (
ModuleNotFoundError: No module named 'win32com'
Traceback (most recent call last):
  File "c:\Users\WESTNB21\Scripts\linecounter.py", line 3, in <module>
    fileName = filechooser.open_file(
    return self._file_selection_dialog(mode="open", *args, **kwargs)
  File "C:\Users\<USER>\scripts\.venv\lib\site-packages\plyer\facades\filechooser.py", line 74, in _file_selection_dialog
    raise NotImplementedError()
NotImplementedError

I am on windows 10, with python 3.10

**Comment by misl6** [comment]
Hi @nWestie 

> Could pywin32 be added as a dependancy of plyer, to reduce confusion? Kivy installs it automatically on windows.

Yes, do you want to take care of the PR and testing? (I do not have a Windows setup available ATM)

**Comment by nWestie** [comment]
sure, I think I can figure out how to do that, I'll give it a shot this week sometime
