### ISSUE TITLE
filechooser raises not implemented error in linux

### ISSUE THREAD

**Issue by rraammiinn** [kivy/plyer#739]
Traceback (most recent call last):
  File "/home/ramin/projects/py/plyr.py", line 3, in <module>
    filechooser.FileChooser().choose_dir()
  File "/home/ramin/projects/py/p/lib/python3.10/site-packages/plyer/facades/filechooser.py", line 69, in choose_dir
    return self._file_selection_dialog(mode="dir", *args, **kwargs)
  File "/home/ramin/projects/py/p/lib/python3.10/site-packages/plyer/facades/filechooser.py", line 74, in _file_selection_dialog
    raise NotImplementedError()
NotImplementedError

**Comment by misl6** [comment]
Can you post a reproducible code snippet and the full log?

**Comment by barries** [comment]
HTH: I ran into this today in a WSL2 environment, installing YAD (Yet Another Dialog) worked for me except that the `YADFileChooser` passes `--file-selection` and YAD 12.3 required `--file` (which I am filing an issue for).

**Comment by barries** [comment]
Thanks. Turns out I needed to install YAD (or any other backend).
