### ISSUE TITLE
[Bug] battery.status gives an error.

### ISSUE THREAD

**Issue by Samuel-de-Oliveira** [kivy/plyer#743]
Is in title, for any reason when I write `battery.status` the following error appears:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/plyer/utils.py", line 117, in __getattribute__
    result = getattr(object.__getattribute__(self, '_obj'), name)
  File "/usr/lib/python3.10/site-packages/plyer/facades/battery.py", line 42, in status
    return self.get_state()
  File "/usr/lib/python3.10/site-packages/plyer/facades/battery.py", line 49, in get_state
    return self._get_state()
  File "/usr/lib/python3.10/site-packages/plyer/platforms/linux/battery.py", line 81, in _get_state
    percentage = float(
ValueError: could not convert string to float: '0% (should be ignored'

```

Edit: I'm using Arch Linux

**Comment by misl6** [comment]
Hi @Samuel-de-Oliveira !

Does this device have a battery?

**Comment by Samuel-de-Oliveira** [comment]
Yes, it actually has.

## About the device:

- *company: * Multilaser
- *Model: * pc312 Legacy

> :information_source: Multilaser is a Brazilian company that make home appliances, smartphones, computers and more.

I hope this usefully.

**Comment by misl6** [comment]
Ok, since looks like we're unable to convert the output into a valid value, and I can't reproduce on my side, can you manually read the output from a console?

See: https://github.com/kivy/plyer/blob/master/plyer/platforms/linux/battery.py for the actual implementation.

**Comment by Samuel-de-Oliveira** [comment]
Well, what I got in console is this:

![this_image](https://user-images.githubusercontent.com/81493939/219110828-c863a95b-56c8-4f40-b1aa-02e140f96675.png)

so I tried to do something and I remove (commented) this following lines:

```python
percentage = float(
      percentage.replace(',', '.')
)
```

and i Got this:

![another_image](https://user-images.githubusercontent.com/81493939/219112164-4c64cedd-e57c-49e1-a820-4d751cfade53.png)

then I concluded that the library doesn't identify my laptop battery. I've tried solve this but I don't have any idea what to do.

**Comment by zencraftr** [comment]
I think I know why @Samuel-de-Oliveira gets the `ValueError`. In linux, depending on the distribution, you may have the primary battery set to **BAT1** instead of **BAT0**.

I checked the source code and it seems **BAT0** is hardcoded to be the default battery for Linux platforms. However, for some distribution this is not the case, it seems **Arch Linux** is one of this distros (at least for me). 

This is the line that gives that hardcodes the problem.
[kernel_bat_path = join('/sys', 'class', 'power_supply', 'BAT0')](https://github.com/kivy/plyer/blob/0cfc2363891f916ad2911d4c0c1f4c3f7f317843/plyer/platforms/linux/battery.py#L22C1-L22C72)

A similar issue was raise for [psutil](https://github.com/giampaolo/psutil/issues/1238) and it got fixed.

I have the same problem in my Arch Linux system, and if I check the primary battery with `upower -e` you can see that I get **BAT1**.

```sh
❯ upower -e
/org/freedesktop/UPower/devices/battery_BAT1
/org/freedesktop/UPower/devices/line_power_ACAD
/org/freedesktop/UPower/devices/DisplayDevice
```

If I forcefully check **BAT0**, it seems to exist but `should be ignored` as percentage property says:
```sh
❯ upower -i /org/freedesktop/UPower/devices/battery_BAT0
  native-path:          (null)
  power supply:         no
  updated:              Thu 01 Jan 1970 01:00:00 BST (1744376463 seconds ago)
  has history:          no
  has statistics:       no
  unknown
    warning-level:       unknown
    battery-level:       unknown
    percentage:          0% (should be ignored)
    icon-name:          '(null)'
```

While if check **BAT1**, then you can see it's the primary battery.
```sh
❯ upower -i /org/freedesktop/UPower/devices/battery_BAT1
  native-path:          BAT1
  ....
  power supply:         yes
  updated:              Fri 11 Apr 2025 14:00:52 BST (8 seconds ago)
  has history:          yes
  has statistics:       yes
  battery
    present:             yes
    rechargeable:        yes
    state:               discharging
    warning-level:       none
    energy:              27.653 Wh
    energy-empty:        0 Wh
    energy-full:         33.532 Wh
    energy-full-design:  41.4279 Wh
    energy-rate:         7.7355 W
    voltage:             11.984 V
    charge-cycles:       701
    time to empty:       3.6 hours
    percentage:          82%
    capacity:            80.9405%
    technology:          lithium-ion
    charge-start-threshold:        75%
    charge-end-threshold:          80%
    charge-threshold-supported:    yes
    icon-name:          'battery-full-symbolic'
  History (charge):
    1744376380	82.000	discharging
  History (rate):
    1744376452	7.736	discharging
    1744376440	7.575	discharging
    1744376410	7.438	discharging
    1744376380	8.114	discharging
    1744376350	7.266	discharging
```
@misl6 I am comfortable to start working on this issue, could you please reopen it?
