### ISSUE TITLE
Pydroid3 devlopment on android GPS permission

### ISSUE THREAD

**Issue by sharpentheaxe** [kivy/plyer#746]
I am developing an application a class for my Master's degree.  I am trying to use pydriod to expidite the development of the python app on my andriod device.  Kivy screens work really well but I tried to query the gps data and I get a requesting permission error.  I did tried to install the pydroid3 permissions app.  I have also searched other issues but may not be hiting the correct keywords.  I am contacting pydroid3 also, if I need to switch over to buildozer to devlop the app I will,  but I would think this woud be a benefit to everyone to develop with pydroid3.  

This is the log of the error that I get:

INFO   ] [Logger      ] Record log in /storage/emulated/0/.kivy/logs/kivy_23-02-19_0.txt
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.9.7 (default, Oct  6 2021, 01:34:26) 
[GCC 11.1.0]
[INFO   ] [Python      ] Interpreter at "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/bin/python3"
[INFO   ] [Logger      ] Purge log fired. Analysing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
gps.py: Android detected. Requesting permissions
 Traceback (most recent call last):
   File "/data/user/0/ru.iiec.pydroid3/files/temp_iiec_codefile.py", line 104, in <module>
     GpsTest().run()
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kivy/app.py", line 949, in run
     self._run_prepare()
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kivy/app.py", line 919, in _run_prepare
     root = self.build()
   File "/data/user/0/ru.iiec.pydroid3/files/temp_iiec_codefile.py", line 75, in build
     self.request_android_permissions()
   File "/data/user/0/ru.iiec.pydroid3/files/temp_iiec_codefile.py", line 58, in request_android_permissions
     request_permissions([Permission.ACCESS_COARSE_LOCATION,
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/android/permissions.py", line 573, in request_permissions
     _RequestPermissionsManager.request_permissions(permissions, callback)
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/android/permissions.py", line 513, in request_permissions
     cls.register_callback()
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/android/permissions.py", line 489, in register_callback
     cls._java_callback = _onRequestPermissionsCallback(cls.python_callback)
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/android/permissions.py", line 442, in __init__
     super().__init__()
   File "jnius/jnius_proxy.pxi", line 28, in jnius.jnius.PythonJavaClass.__init__
   File "jnius/jnius_proxy.pxi", line 34, in jnius.jnius.PythonJavaClass._init_j_self_ptr
   File "jnius/jnius_proxy.pxi", line 168, in jnius.jnius.create_proxy_instance
   File "jnius/jnius_export_func.pxi", line 26, in jnius.jnius.find_javaclass
   File "jnius/jnius_utils.pxi", line 91, in jnius.jnius.check_exception
 jnius.jnius.JavaException: JVM exception occurred: org.kivy.android.PythonActivity$PermissionsCallback java.lang.ClassNotFoundException

**Comment by sharpentheaxe** [comment]
I figured out that this is not a permission issue.  
There is actually underlying issue with the plyer gps java call.  Similar issue to this https://stackoverflow.com/questions/70763195/kivy-plyer-gps-not-working-after-update-to-android-12

Going to keep investigating via discord.
