### ISSUE TITLE
NotImplementedError (filechooser) after packaging with pyinstaller on Mac

### ISSUE THREAD

**Issue by yas0nia** [kivy/plyer#761]
Hey there! Plyer filechooser.open_file() works perfectly fine in dev, but after packaging the app with pyinstaller it crashes with NotImplementedError.

OS: MacOS Monterrey 12.6 (M1 Apple Silicon)

Code snippet: 

```
from plyer import filechooser

def file_chooser(self):
		filechooser.open_file(
			title='Select an Excel file', filters=[('Excel files', '*.xlsx')], on_selection=self.filechooser_callback)
```

Error itself:

```
[31249] Failed to execute script 'main' due to unhandled exception: 
[31249] Traceback:
Traceback (most recent call last):
  File "main.py", line 187, in <module>
    MyApp().run()
  File "kivy/app.py", line 955, in run
  File "kivy/base.py", line 574, in runTouchApp
  File "kivy/base.py", line 339, in mainloop
  File "kivy/base.py", line 383, in idle
  File "kivy/base.py", line 334, in dispatch_input
  File "kivy/base.py", line 263, in post_dispatch_input
  File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "kivy/core/window/__init__.py", line 1660, in on_motion
  File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "kivy/core/window/__init__.py", line 1677, in on_touch_down
  File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "kivy/uix/screenmanager.py", line 1210, in on_touch_down
  File "kivy/uix/widget.py", line 589, in on_touch_down
  File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "kivy/uix/relativelayout.py", line 306, in on_touch_down
  File "kivy/uix/widget.py", line 589, in on_touch_down
  File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "kivy/uix/widget.py", line 589, in on_touch_down
  File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "kivy/uix/widget.py", line 589, in on_touch_down
  File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "kivy/uix/widget.py", line 589, in on_touch_down
  File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "kivymd/uix/button/button.py", line 1173, in on_touch_down
  File "kivymd/uix/behaviors/ripple_behavior.py", line 352, in on_touch_down
  File "kivy/uix/behaviors/button.py", line 151, in on_touch_down
  File "kivy/_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
  File "kivy/_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
  File "kivy/_event.pyx", line 1191, in kivy._event.EventObservers._dispatch
  File "kivy/lang/builder.py", line 55, in custom_callback
  File "/Users/yas0nia/Desktop/work/dist/DPLchecker/my.kv", line 73, in <module>
    on_press: root.file_chooser()
  File "main.py", line 31, in file_chooser
    filechooser.open_file(
  File "plyer/facades/filechooser.py", line 54, in open_file
  File "plyer/facades/filechooser.py", line 74, in _file_selection_dialog
NotImplementedError
```

**Comment by akshayaurora** [comment]
hiddenimports=['...', 'plyer', 'plyer.platforms.win.filechooser', ...] try adding this .
